 const menuList= [
  {
    id: 1,
    name: "首页",
    type: 2,
    path: "/home",
    index: "1",
    icon: "iconfont icon-home",
  },
  {
    id: 2,
    type: 1,
    name: "实习管理",
    index: "2",
    icon: "iconfont icon-shixishengguanli",
    children: [
      {
        id: 1,
        type: 2,
        name: "实习申请",
        path: "/apply",
        index: "2-1",
        icon: "iconfont icon-custom-apply",
      },
      {
        id: 2,
        type: 2,
        name: "实习变更",
        path: "/change",
        index: "2-2",
        icon: "iconfont icon-change",
      },
    ],
  },
  {
    id: 3,
    type: 1,
    name: "实习考核",
    index: "3",
    icon: "iconfont icon-SCORE_SET",
    children: [
      {
        id: 1,
        type: 2,
        name: "实习日报",
        path: "/dayNews",
        index: "3-1",
        icon: "iconfont icon-news",
      },
      {
        id: 2,
        type: 2,
        name: "实习总结",
        path: "/summary",
        index: "3-2",
        icon: "iconfont icon-loan_summary",
      },
      {
        id: 3,
        type: 2,
        name: "实习成绩",
        path: "/grade",
        index: "3-3",
        icon: "iconfont icon-SCORE_SET",
      },
    ],
  },
  {
    id: 4,
    type: 1,
    name: "请假管理",
    index: "4",
    icon: "iconfont icon-faculty-leave",
    children: [
      {
        id: 1,
        type: 2,
        name: "请假申请",
        path: "/leave",
        index: "4-1",
        icon: "iconfont icon-faculty-leave",
      },
    ],
  },
  {
    id: 5,
    type: 1,
    name: "关于我的",
    index: "5",
    icon: "iconfont icon-user",
    children: [
      {
        id: 1,
        type: 2,
        name: "个人中心",
        path: "/person_center",
        index: "5-1",
        icon: "iconfont icon-user",
      },
      {
        id: 2,
        type: 2,
        name: "编辑资料",
        path: "/self_edit",
        index: "5-1",
        icon: "iconfont icon-bianjiziliao",
      },
    ],
  },
  {
    id: 6,
    type: 2,
    name: "草稿箱",
    path: "/draft",
    index: "6",
    icon: "iconfont icon-caogaoxiang-",
  },
];
export default menuList